import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import {ThemeProvider} from 'next-themes'
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};     
      
export default function RootLayout({ children }) {
  // this is the rsc
  // error as this is theme provider are working on the context which is hook and only render on the use client mode
   
  
  return (
    <html lang="en">
      <body className={inter.className}>
         <ThemeProvider>

           <Providers>
                <Header/>
                
                <main>
                
                  {children}
                
                </main>
                
                <Footer/>
                {/* these are pass to the Providers and access there with the of {childrens} */}
            </Providers>
             {/*pass them as props to the theme providers this is how prop works  */}
         </ThemeProvider>
      </body>
    </html>
  );
}
// all the chidlrens from the folder app has are rendered with ui along with the route pathname
// about and contact are rendered in the root layout so it seen layout is formed to rendered theire chidren route with their ui

